on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: UI/codepulse

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Angular
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: ng build
    - name: Start
      run: ng serve
    - name: Test
      run: ng test